In [50]:
import numpy as np
import pandas as pd

V = 10000
F = 0.85
M = 4
rate = 0.02 / 12

df = pd.read_excel('CPPI.xlsx')
#df = pd.read_excel('./2022디지털금융/1st 1학기/디지털금융 프로그래밍/실습코드/5주차 강의 실습코드/ex) portfolio insurance/CPPI.xlsx')
df['ret'] = df['sp500'].pct_change()
df['stock100'] = df['ret'] + 1
df.loc[0, 'stock100'] = V
df['stock100']  = df['stock100'].cumprod()
df

          date    sp500       ret      stock100
0   2000-01-31  1394.46       NaN  10000.000000
1   2000-02-29  1366.42 -0.020108   9798.918578
2   2000-03-31  1498.58  0.096720  10746.668961
3   2000-04-28  1452.43 -0.030796  10415.716478
4   2000-05-31  1420.60 -0.021915  10187.456076
5   2000-06-30  1454.60  0.023934  10431.278057
6   2000-07-31  1430.83 -0.016341  10260.817808
7   2000-08-31  1517.68  0.060699  10883.639545
8   2000-09-29  1436.51 -0.053483  10301.550421
9   2000-10-31  1429.40 -0.004949  10250.562942
10  2000-11-30  1314.95 -0.080069   9429.815126
11  2000-12-29  1320.28  0.004053   9468.037807
12  2001-01-31  1366.01  0.034637   9795.978372
13  2001-02-28  1239.94 -0.092291   8891.900807
14  2001-03-30  1160.33 -0.064205   8320.998810
15  2001-04-30  1249.46  0.076814   8960.170962
16  2001-05-31  1255.82  0.005090   9005.780015
17  2001-06-29  1224.42 -0.025004   8780.603244
18  2001-07-31  1211.23 -0.010772   8686.014658
19  2001-08-31  1133.58 -0.064108   8129.168280
20  2001-09-28  1040.94 -0.081723   7464.825094
21  2001-10-31  1059.78  0.018099   7599.931156
22  2001-11-30  1139.45  0.075176   8171.263428
23  2001-12-31  1148.08  0.007574   8233.151184
24  2002-01-31  1130.20 -0.015574   8104.929507
25  2002-02-28  1106.73 -0.020766   7936.620627
26  2002-03-28  1147.39  0.036739   8228.203032
27  2002-04-30  1076.92 -0.061418   7722.846120
28  2002-05-31  1067.14 -0.009081   7652.711444
29  2002-06-28   989.81 -0.072465   7098.159861
..         ...      ...       ...           ...
234 2019-07-31  2980.38  0.013128  21373.004604
235 2019-08-30  2926.46 -0.018092  20986.331627
236 2019-09-30  2976.74  0.017181  21346.901309
237 2019-10-31  3037.56  0.020432  21783.055807
238 2019-11-29  3140.98  0.034047  22524.704904
239 2019-12-31  3230.78  0.028590  23168.681784
240 2020-01-31  3225.52 -0.001628  23130.961089
241 2020-02-28  2954.22 -0.084110  21185.405103
242 2020-03-31  2584.59 -0.125119  18534.701605
243 2020-04-30  2912.43  0.126844  20885.719203
244 2020-05-29  3044.31  0.045282  21831.461641
245 2020-06-30  3100.29  0.018388  22232.907362
246 2020-07-31  3271.12  0.055101  23457.969393
247 2020-08-31  3500.31  0.070065  25101.544684
248 2020-09-30  3363.00 -0.039228  24116.862441
249 2020-10-30  3269.96 -0.027666  23449.650761
250 2020-11-30  3621.63  0.107546  25971.558883
251 2020-12-31  3756.07  0.037121  26935.659682
252 2021-01-29  3714.24 -0.011137  26635.686933
253 2021-02-26  3811.15  0.026091  27330.651292
254 2021-03-31  3972.89  0.042439  28490.526799
255 2021-04-30  4181.17  0.052425  29984.151571
256 2021-05-28  4204.11  0.005487  30148.659696
257 2021-06-30  4297.50  0.022214  30818.381309
258 2021-07-30  4395.26  0.022748  31519.441217
259 2021-08-31  4522.68  0.028990  32433.199948
260 2021-09-30  4307.54 -0.047569  30890.380506
261 2021-10-29  4605.38  0.069144  33026.261062
262 2021-11-30  4567.00 -0.008334  32751.029072
263 2021-12-31  4766.18  0.043613  34179.395608

[264 rows x 4 columns]

In [51]:
# 초기화
df.loc[0, 'CPPI'] = V
df.loc[:, 'floor'] = V * F
df.loc[0, 'cushion'] = df.loc[0, 'CPPI'] - V * F
df.loc[0, 'stock'] = df.loc[0, 'cushion'] * M
df.loc[0, 'CMA'] = df.loc[0, 'CPPI'] - df.loc[0, 'stock']
df.loc[0, 'ratio'] = df.loc[0, 'stock'] / df.loc[0, 'CPPI']

for i in df.index: 
    if i == 0:
        continue
    
    #CPPI
    df['CPPI'][i] = df['stock'][i-1] * (1 + df['ret'][i]) + df['CMA'][i-1] * (1 + rate)
    #cushion
    df['cushion'][i] = max(df['CPPI'][i] - V * F, 0)
    #stock
    df['stock'][i] = min(df['cushion'][i]*M, df.loc[i, 'CPPI'])
    #CMA
    df['CMA'][i] = df['CPPI'][i] - df['stock'][i]
    #ratio
    df['ratio'][i] = df['stock'][i]/df['CPPI'][i]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy