In [29]:
import numpy as np
import pandas as pd

In [101]:
df = pd.read_excel('historical simulation.xlsx', header=8)
df.head()

,Day,Date,S&P500,FTSE 100,CAC40,Nikkei 225,USD/GBP,EUR/USD,JPY/USD
0,0,2018-05-09,5292.899902,6515.12,14248.81,35149.26,1.355344,0.84261,109.024002
1,1,2018-05-10,5343.700195,6590.48,14277.96,35287.76,1.354463,0.84408,109.847000
2,2,2018-05-11,5354.689941,6642.39,14319.78,35697.62,1.352338,0.83910,109.435997
3,3,2018-05-14,5359.660156,6639.69,14325.19,35866.05,1.355381,0.83667,109.337997
4,4,2018-05-15,5323.229980,6638.76,14357.45,35791.01,1.356245,0.83814,109.731003

In [102]:
sp500 = 4000
ftse100 = 3000
cac40 = 1000
nikkei225 = 2000
tot = sp500 + ftse100 + cac40 + nikkei225

df['FTSE100($)']  = df.loc[:, 'FTSE 100']*df.loc[:, 'USD/GBP']
df['CAC400($)'] = df.loc[:, 'CAC40'] / df.loc[:, 'EUR/USD']
df['Nikkei225($)'] = df.loc[:, 'Nikkei 225'] / df.loc[:, 'JPY/USD']
df = df.drop(columns=['Date','FTSE 100', 'CAC40', 'Nikkei 225', 'USD/GBP', 'EUR/USD', 'JPY/USD'], axis=1)
df = df.rename(columns={'Day':'Scenario'})

In [103]:
for i in range(len(df)-1):
    df.loc[i, 'S&P500'] = sp500 * df.loc[i+1, 'S&P500'] / df.loc[i, 'S&P500']
    df.loc[i, 'FTSE100($)'] = ftse100 * df.loc[i+1, 'FTSE100($)'] / df.loc[i, 'FTSE100($)'] 
    df.loc[i, 'CAC400($)'] = cac40 * df.loc[i+1, 'CAC400($)'] / df.loc[i, 'CAC400($)'] 
    df.loc[i, 'Nikkei225($)'] = nikkei225 * df.loc[i+1, 'Nikkei225($)'] / df.loc[i, 'Nikkei225($)'] 
    portfolioValue = 0
    for j in range(1, 5):
        portfolioValue += df.iloc[i, j]
    df.loc[i, 'portfolio value'] = portfolioValue
    df.loc[i, 'P/L'] = df.loc[i, 'portfolio value'] - tot
    df.loc[i, 'P/L(%)'] = df.loc[i, 'P/L'] / 100 
    
df = df.drop(index=500)
df.loc[:, 'Scenario'] = df.loc[:, 'Scenario'] + 1
df = df.round(2)
df = df.sort_values('P/L')
df.set_index('Scenario')

,S&P500,FTSE100($),CAC400($),Nikkei225($),portfolio value,P/L,P/L(%)
Scenario,,,,,,,
427,3620.34,2663.72,872.97,1920.49,9077.52,-922.48,-9.22
429,3520.81,2767.97,940.02,1912.78,9141.58,-858.42,-8.58
424,3696.53,2779.70,929.33,1940.90,9346.46,-653.54,-6.54
415,3749.44,2860.74,947.29,1952.31,9509.78,-490.22,-4.90
482,3764.68,2898.86,955.73,1958.43,9577.71,-422.29,-4.22
440,3823.46,2937.78,956.70,1919.33,9637.27,-362.73,-3.63
426,3804.81,2928.48,987.21,1918.97,9639.47,-360.53,-3.61
431,3792.70,2980.84,928.20,1944.48,9646.21,-353.79,-3.54
417,3824.14,2927.82,967.11,1957.42,9676.49,-323.51,-3.24
433,3715.12,2987.51,990.51,2001.65,9694.78,-305.22,-3.05
452,3877.41,2954.32,962.59,1960.53,9754.85,-245.15,-2.45
418,3967.70,2875.68,976.09,1938.97,9758.44,-241.56,-2.42
140,3995.16,2859.63,953.19,1960.75,9768.73,-231.27,-2.31
289,3881.09,2926.67,980.66,1980.95,9769.37,-230.63,-2.31
152,3891.85,2998.39,978.29,1901.79,9770.32,-229.68,-2.30
423,3931.91,2912.94,965.89,1971.84,9782.58,-217.42,-2.17
103,3917.72,2952.35,983.07,1937.67,9790.82,-209.18,-2.09
448,3912.13,2918.46,967.88,2000.61,9799.08,-200.92,-2.01
326,3928.38,2905.42,971.90,1996.39,9802.09,-197.91,-1.98
397,3937.07,2941.06,970.61,1972.91,9821.65,-178.35,-1.78
139,3870.77,3003.14,993.96,1955.30,9823.17,-176.83,-1.77
491,3896.60,2947.40,973.65,2007.50,9825.15,-174.85,-1.75
111,3978.15,2929.23,979.51,1941.80,9828.68,-171.32,-1.71
295,3883.97,2973.46,975.56,1996.18,9829.17,-170.83,-1.71
150,3937.00,2970.71,983.43,1945.24,9836.38,-163.62,-1.64
432,4019.12,2841.37,1021.78,1961.27,9843.54,-156.46,-1.56
459,3959.26,2946.35,982.30,1956.29,9844.21,-155.79,-1.56
146,3924.14,2979.78,990.32,1954.79,9849.03,-150.97,-1.51
102,3868.57,2998.47,980.55,2004.88,9852.47,-147.53,-1.48
422,3865.14,3003.02,977.36,2009.70,9855.22,-144.78,-1.45
...,...,...,...,...,...,...,...
333,4044.13,3060.14,1019.47,2009.75,10133.49,133.49,1.33
292,4076.08,3024.03,1022.82,2011.57,10134.50,134.50,1.35
309,4052.97,3036.74,1016.65,2033.39,10139.75,139.75,1.40
155,4075.96,3045.28,1008.94,2010.00,10140.17,140.17,1.40
444,3993.63,3097.60,1020.90,2032.36,10144.50,144.50,1.44
476,4055.00,3049.70,1039.73,2002.34,10146.77,146.77,1.47
475,4032.97,3077.93,1021.23,2026.87,10159.00,159.00,1.59
456,4058.93,3015.77,1029.92,2057.41,10162.02,162.02,1.62
106,4086.10,3027.93,1018.13,2031.31,10163.47,163.47,1.63
471,4059.39,3070.55,1025.27,2017.59,10172.79,172.79,1.73
458,4068.79,3044.08,1005.37,2055.63,10173.87,173.87,1.74
460,4069.01,3045.44,1002.55,2058.66,10175.66,175.66,1.76
478,4104.90,3020.89,1046.48,2012.02,10184.28,184.28,1.84
465,4126.48,2993.64,1053.00,2012.55,10185.66,185.66,1.86
438,4134.73,3030.77,1016.25,2018.35,10200.10,200.10,2.00
428,4372.83,2941.96,1011.40,1877.31,10203.50,203.50,2.03
450,4107.34,3019.23,1029.79,2056.52,10212.88,212.88,2.13
470,4049.22,3047.83,1031.65,2085.53,10214.24,214.24,2.14
445,4137.20,3028.04,1009.47,2051.26,10225.97,225.97,2.26
425,4197.70,3012.96,985.89,2033.25,10229.80,229.80,2.30
447,4081.22,3085.26,1009.27,2054.76,10230.51,230.51,2.31
419,4184.25,2997.52,1009.39,2055.83,10246.98,246.98,2.47
421,4169.03,3033.14,1016.63,2028.76,10247.56,247.56,2.48
153,4234.80,2946.54,992.99,2097.34,10271.67,271.67,2.72
436,4249.85,3076.45,1033.36,1913.96,10273.61,273.61,2.74
485,4075.92,3088.10,1036.23,2094.66,10294.91,294.91,2.95
430,4239.95,3016.26,1029.14,2010.79,10296.14,296.14,2.96
443,4281.38,2968.02,1042.21,2071.59,10363.19,363.19,3.63
435,4046.15,3299.22,1048.38,2155.06,10548.81,548.81,5.49
434,4375.74,3036.15,1091.87,2135.60,10639.36,639.36,6.39