In [3]:
count = ewret.groupby(['momr'])['momr'].count().to_frame().rename(columns={'momr':'count'})
mean = ewret.groupby(['momr'])['ewret'].mean().to_frame()
std = ewret.groupby(['momr'])['ewret'].std().to_frame()
pd.concat([count, mean, std], axis=1)

      count     ewret     ewret
momr
1       300  0.008512  0.087290
2       300  0.011570  0.070502
3       300  0.012843  0.064907
4       300  0.013016  0.061133
5       300  0.013443  0.058722
6       300  0.014016  0.057706
7       300  0.014049  0.057390
8       300  0.014743  0.058601
9       300  0.015583  0.061539
10      300  0.016934  0.069849

In [2]:
import numpy as np
import pandas as pd
from pandas.tseries.offsets import *
from scipy import stats

crsp = pd.read_csv('crsp.csv')
crsp['date'] = pd.to_datetime(crsp['date'])
#crsp['ret'] = crsp['ret'].fillna(0)
crsp = crsp[crsp['ret'].notna()] # 해당월의 holding portfolio 제외

J = 6
K = 6
crsp.sort_values(['permno', 'date'], inplace=True, ignore_index=True)
crsp['logret'] = np.log(1 + crsp['ret'])
crsp = crsp.set_index('date')

umd = crsp.groupby('permno')['logret'].rolling(J).sum()
umd = umd.reset_index()
umd['cumret'] = np.exp(umd['logret']) - 1

umd.dropna(subset=['cumret'], inplace=True)
umd['momr'] = umd.groupby('date')['cumret'].transform(lambda x: pd.qcut(x, 10, labels=False))
umd['momr'] = umd['momr'] + 1

umd['medate'] = umd['date'] + MonthEnd(0)
umd['hdate1'] = umd['medate'] + MonthBegin(1)
umd['hdate2'] = umd['medate'] + MonthEnd(K)
umd['form_date'] = umd['date']
umd = umd[['permno', 'form_date', 'momr', 'hdate1', 'hdate2']]
crsp.reset_index(inplace=True)
crsp = crsp[['permno', 'date', 'ret']]

port = pd.DataFrame()
n = 100000
for i in range(0, crsp.shape[0], n):
    tmp = crsp.iloc[i: i+n]
    merged = umd.merge(tmp, on=['permno'], how='inner')
    merged = merged[(merged['hdate1'] <= merged['date'])\
                   & (merged['date'] <= merged['hdate2'])]
    port = pd.concat([port, merged])

umd2 = port.groupby(['date', 'momr', 'form_date'])['ret'].mean().reset_index()
start_year = 1965
umd2 = umd2[umd2['date'].dt.year >= start_year]
ewret = umd2.groupby(['date', 'momr'])['ret'].mean().reset_index()
ewret.rename(columns={'ret': 'ewret'}, inplace=True)
ewret.groupby(['momr'])['ewret'].describe()[['count', 'mean', 'std']]

ewret2 = ewret.pivot(index='date', columns='momr', values='ewret')
ewret2 = ewret2.add_prefix('port')
ewret2 = ewret2.rename(columns={'port1':'losers', 'port10':'winners'})
ewret2['long_short'] = ewret2['winners'] - ewret2['losers']

mom_mean = ewret2[['winners', 'losers', 'long_short']].mean().to_frame()
mom_mean = mom_mean.rename(columns={0:'mean'}).reset_index()

t_losers = pd.Series(stats.ttest_1samp(ewret2['losers'], 0.0)).to_frame().T
t_winners = pd.Series(stats.ttest_1samp(ewret2['winners'], 0.0)).to_frame().T
t_long_short = pd.Series(stats.ttest_1samp(ewret2['long_short'], 0.0)).to_frame().T
t_output = pd.concat([t_winners, t_losers, t_long_short])\
            .rename(columns={0:'t-stat', 1:'p-value'})
t_output['momr'] = ['winners', 'losers', 'long_short']
pd.merge(mom_mean, t_output, on=['momr'], how='inner')

         momr      mean    t-stat   p-value
0     winners  0.016934  4.199180  0.000035
1      losers  0.008512  1.689002  0.092261
2  long_short  0.008422  2.782792  0.005732